Repository WalkMe/teachme-admin, pull requests merged in 2020-09, with the labels that each got.

#267 Remove ability to order by time to complete
  src/components/Screen/UsersScreen/tableData.tsx
Labels: code review

#269 Courses table selection bugs
  package-lock.json
  package.json
  src/components/Screen/CoursesScreen/index.tsx
  src/components/Screen/CoursesScreen/style.module.scss
  src/components/Screen/CoursesScreen/tableData.tsx
Labels: bug, code review

#273 quiz-completion-rate-bug
  src/components/common/AnalyticsCharts/QuizCompletionRateChart/QuizCompletionRateLegend.tsx
  src/components/common/charts/PieBarChart/index.tsx
Labels: bug, code review

#274 Course editor outline buttons bug fixes
  src/components/Screen/CourseEditorScreen/CourseOutlineQuiz/style.module.scss
  src/components/common/buttons/AddButton/style.module.scss
Labels: bug, code review

#275 Makes date range popup close on scroll
  src/components/common/filters/TimeFilter/index.tsx
  src/components/common/filters/TimeFilter/style.module.scss
  src/hooks/useEventListener.ts
Labels: bug

#276 Fixing safari user-select issue
  src/components/Screen/CoursesScreen/style.module.scss
  src/components/common/WMTable/index.tsx
Labels: code review

#277 Fixing general validation error message
  src/components/Screen/CourseEditorScreen/CourseEditorHeader.tsx
  src/components/Screen/CourseEditorScreen/HeaderConfirmationButtons.tsx
  src/components/Screen/CourseEditorScreen/index.tsx
Labels: bug, code review

#281 Fixed areAllRowsSelected state
  src/components/Screen/CoursesScreen/SearchCoursesFilter.tsx
  src/components/Screen/CoursesScreen/index.tsx
Labels: code review

#284 Users table width fix
  src/components/Screen/UsersScreen/style.module.scss
  src/components/Screen/UsersScreen/tableData.tsx
  src/components/common/tableCells/TextCell.tsx
  src/components/common/tableCells/style.module.scss
  src/components/common/tableCells/tableCells.interface.ts
Labels: bug

#289 Fix quiz avg
  src/components/Screen/CoursesScreen/tableData.tsx
  src/components/common/AnalyticsCharts/utils.ts
Labels: code review

#290 reset table rows selection on system change
  src/components/Screen/CoursesScreen/index.tsx
Labels: bug
