Repository WalkMe/teachme-admin, pull requests merged in 2020-08, with the labels that each got.

#112 Single course analytics provider integration
  src/components/Screen/CourseEditorScreen/CourseOutlineQuiz/QuestionItem.tsx
  src/components/Screen/CourseScreen/CourseTabs.tsx
  src/components/Screen/CourseScreen/index.tsx
  src/components/Screen/CoursesScreen/index.tsx
  src/components/Screen/UsersScreen/index.tsx
  src/components/common/AnalyticsCharts/QuizScoreChart/index.tsx
  src/components/common/AnalyticsCharts/analytics.interface.ts
  src/components/common/AnalyticsCharts/index.tsx
  src/components/common/CourseQuizTabCharts/index.tsx
  src/components/common/charts/WMHorizontalBarChart/index.tsx
  src/constants/mocks/course-screen.ts
Labels: code review

#120 Single course outline integration
  package-lock.json
  package.json
  src/components/Screen/CourseScreen/CourseOutlineTable.tsx
  src/components/Screen/CourseScreen/CourseScreenHeader.tsx
  src/components/Screen/CourseScreen/CourseTabs.tsx
  src/components/Screen/CourseScreen/courseScreen.interface.ts
  src/components/Screen/CourseScreen/index.tsx
  src/components/Screen/CourseScreen/style.module.scss
  src/components/Screen/CourseScreen/tableData.tsx
  src/components/Screen/CourseScreen/utils.ts
  src/components/common/AnalyticsCharts/CourseTimeCompletionChart/CourseTimeCompletionLegend.tsx
  src/components/common/AnalyticsCharts/CourseTimeCompletionChart/index.tsx
  src/components/common/AnalyticsCharts/QuizScoreChart/index.tsx
  src/components/common/AnalyticsCharts/analytics.interface.ts
  src/components/common/AnalyticsCharts/index.tsx
  src/components/common/AnalyticsCharts/utils.ts
  src/components/common/CourseQuizTabCharts/index.tsx
  src/components/common/WMTable/WMTableExpanded.tsx
  src/components/common/WMTable/index.tsx
  src/components/common/WMTable/style.module.scss
  src/components/common/charts/WMHorizontalBarChart/index.tsx
  src/components/common/charts/WMHorizontalBarChart/style.module.scss
  src/providers/CourseContext/actions.ts
  src/providers/CourseContext/course-context.interface.ts
  src/providers/CourseContext/reducer.ts
  src/providers/CourseContext/utils.ts
Labels: code review

#125 hash-router
  package-lock.json
  package.json
  src/components/Layout/index.tsx
Labels: code review

#124 Course segments
  src/components/Screen/CourseScreen/CourseScreenHeader.tsx
  src/components/Screen/CourseScreen/index.tsx
  src/providers/CourseContext/course-context.interface.ts
  src/providers/CourseContext/reducer.ts
  src/providers/CourseContext/utils.ts
Labels: code review

#123 Courses table sorting
  src/components/Screen/CoursesScreen/CoursesEmptyState.tsx
  src/components/Screen/CoursesScreen/index.tsx
  src/components/Screen/CoursesScreen/style.module.scss
  src/components/common/WMTable/index.tsx
  src/providers/CoursesContext/actions.ts
  src/providers/CoursesContext/courses-context.interface.ts
  src/providers/CoursesContext/index.tsx
  src/providers/CoursesContext/reducer.ts
  src/providers/CoursesContext/utils.ts
Labels: code review

#130 Course editor quiz actions
  src/components/Screen/CourseEditorScreen/ActionMenu.tsx
  src/components/Screen/CourseEditorScreen/CourseItemsList/index.tsx
  src/components/Screen/CourseEditorScreen/CourseOutlineLessonItem/index.tsx
  src/components/Screen/CourseEditorScreen/CourseOutlineList/index.tsx
  src/components/Screen/CourseEditorScreen/CourseOutlineQuiz/CourseQuestionList.tsx
  src/components/Screen/CourseEditorScreen/CourseOutlineQuiz/DraggableQuestionItem.tsx
  src/components/Screen/CourseEditorScreen/CourseOutlineQuiz/QuestionItem.tsx
  src/components/Screen/CourseEditorScreen/CourseOutlineQuiz/index.tsx
  src/components/Screen/CourseEditorScreen/CourseOutlineQuiz/style.module.scss
  src/components/Screen/CourseEditorScreen/CourseOutlineTab.tsx
  src/components/Screen/CourseEditorScreen/LessonHeader/style.module.scss
  src/components/Screen/CourseEditorScreen/QuizEditForm/Answers.tsx
  src/components/Screen/CourseEditorScreen/QuizEditForm/QuestionScreenForm.tsx
  src/components/Screen/CourseEditorScreen/QuizEditForm/style.module.scss
  src/components/Screen/CourseEditorScreen/QuizHeader/index.tsx
  src/components/Screen/CourseEditorScreen/QuizHeader/style.module.scss
  src/components/Screen/CourseEditorScreen/TaskItem/index.tsx
  src/components/Screen/CourseEditorScreen/TaskItem/style.module.scss
  src/components/Screen/Playground/components/QuizEdit.tsx
  src/components/common/Icon/icon.interface.ts
  src/components/common/Icon/iconsSVG.tsx
  src/components/common/WMDropdown/index.tsx
  src/components/common/WMDropdown/style.module.scss
  src/images/icons/settings.svg
Labels: code review

#136 Course editor validation
  src/components/Screen/CourseEditorScreen/CourseOutlineQuiz/DraggableQuestionItem.tsx
  src/components/Screen/CourseEditorScreen/CourseOutlineQuiz/QuestionItem.tsx
  src/components/Screen/CourseEditorScreen/CourseOutlineQuiz/index.tsx
  src/components/Screen/CourseEditorScreen/CourseOutlineQuiz/style.module.scss
  src/components/Screen/CourseEditorScreen/HeaderConfirmationButtons.tsx
  src/components/Screen/CourseEditorScreen/QuizEditForm/Answers.tsx
  src/components/Screen/CourseEditorScreen/QuizEditForm/QuestionScreenForm.tsx
  src/components/Screen/CourseEditorScreen/QuizEditForm/style.module.scss
  src/components/Screen/CourseEditorScreen/style.module.scss
  src/components/common/Icon/icon.interface.ts
  src/components/common/Icon/iconsSVG.tsx
  src/images/icons/validation-error.svg
  src/walkme/data/courseBuild/defaults.ts
  src/walkme/data/courseBuild/quiz/question/index.ts
Labels: code review

#138 Courses screen skeleton
  src/components/Screen/CoursesScreen/ShownCoursesIndicator.tsx
  src/components/Screen/CoursesScreen/index.tsx
  src/components/Screen/CoursesScreen/style.module.scss
  src/components/common/AnalyticsCharts/CourseSummaryChart/index.tsx
  src/components/common/AnalyticsCharts/CourseTimeCompletionChart/index.tsx
  src/components/common/AnalyticsCharts/QuizCompletionRateChart/index.tsx
  src/components/common/AnalyticsCharts/QuizScoreChart/index.tsx
  src/components/common/AnalyticsCharts/analytics.interface.ts
  src/components/common/AnalyticsCharts/index.tsx
  src/components/common/WMLegend/index.tsx
  src/components/common/WMTable/SortableRow.tsx
  src/components/common/WMTable/index.tsx
  src/components/common/charts/WMLineChart/index.tsx
  src/components/common/charts/WMLineChart/wmLineChart.interface.ts
  src/components/common/charts/WMProgress/index.tsx
  src/components/common/charts/index.ts
Labels: code review

#140 Single course meta data
  src/components/Screen/CourseScreen/CourseOutlineTable.tsx
  src/components/Screen/CourseScreen/CourseScreenHeader.tsx
  src/components/Screen/CourseScreen/ExportCourseButton.tsx
  src/components/Screen/CourseScreen/index.tsx
  src/components/Screen/CoursesScreen/tableData.tsx
  src/providers/CourseContext/course-context.interface.ts
  src/providers/CourseContext/reducer.ts
  src/providers/CourseContext/utils.ts
  src/utils/index.ts
  src/utils/publish-status.ts
  src/walkme/data/courseList.ts
  src/walkme/data/courseMetadata.ts
Labels: code review

#139 Course screen skeleton
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/walkme-fav.png
  src/components/Screen/CourseScreen/CourseOutlineTable.tsx
  src/components/Screen/CourseScreen/CourseTabs.tsx
  src/components/Screen/CourseScreen/index.tsx
  src/components/Screen/CourseScreen/style.module.scss
  src/components/common/AnalyticsCharts/index.tsx
  src/components/common/WMTable/WMTableExpanded.tsx
  src/components/common/WMTable/index.tsx
  src/components/common/buttons/CreateButton/index.tsx
Labels: code review

#142 Add loader to 'Users' table
  src/components/Screen/UsersScreen/index.tsx
Labels: code review

#148 `CourseEditor`: Redirect on system change
  public/manifest.json
  src/components/Screen/CourseEditorScreen/index.tsx
  src/components/Screen/CourseScreen/index.tsx
  src/hooks/index.ts
  src/hooks/useRedirectToMain.ts
  src/providers/CourseEditorContext/utils.ts
Labels: code review

#149 Add skeleton to course editor
  src/components/Screen/CourseEditorScreen/CourseOutlineTab.tsx
  src/components/Screen/CourseEditorScreen/ResourcesList.tsx
  src/components/Screen/CourseEditorScreen/style.module.scss
Labels: code review

#146 Scroll to added quiz & lesson
  package-lock.json
  package.json
  src/components/Screen/CourseEditorScreen/ActionMenu.tsx
  src/components/Screen/CourseEditorScreen/CourseOutlineLessonItem/index.tsx
  src/components/Screen/CourseEditorScreen/CourseOutlineList/index.tsx
  src/components/Screen/CourseEditorScreen/CourseOutlineQuiz/index.tsx
  src/components/Screen/CourseEditorScreen/CourseOutlineQuiz/style.module.scss
  src/components/Screen/CourseEditorScreen/CourseOutlineTab.tsx
  src/components/Screen/Playground/components/QuizEdit.tsx
  src/components/common/WMCollapse/index.tsx
Labels: code review

#150 V0.12.0
  package-lock.json
  package.json
  public/manifest.json
  src/components/Screen/CourseEditorScreen/ActionMenu.tsx
  src/components/Screen/CourseEditorScreen/CourseOutlineLessonItem/index.tsx
  src/components/Screen/CourseEditorScreen/CourseOutlineList/index.tsx
  src/components/Screen/CourseEditorScreen/CourseOutlineList/style.module.scss
  src/components/Screen/CourseEditorScreen/CourseOutlineQuiz/index.tsx
  src/components/Screen/CourseEditorScreen/CourseOutlineQuiz/style.module.scss
  src/components/Screen/CourseEditorScreen/CourseOutlineTab.tsx
  src/components/Screen/CourseEditorScreen/LessonHeader/DeleteLessonDialog.tsx
  src/components/Screen/CourseEditorScreen/LessonHeader/EditbaleLessonTitle.tsx
  src/components/Screen/CourseEditorScreen/LessonHeader/LessonDeleteButton.tsx
  src/components/Screen/CourseEditorScreen/LessonHeader/style.module.scss
  src/components/Screen/CourseEditorScreen/ResourcesList.tsx
  src/components/Screen/CourseEditorScreen/index.tsx
  src/components/Screen/CourseEditorScreen/style.module.scss
  src/components/Screen/CourseScreen/index.tsx
  src/components/Screen/Playground/components/Dialogs.tsx
  src/components/Screen/Playground/components/QuizEdit.tsx
  src/components/common/UnloadDialog/index.tsx
  src/components/common/WMCollapse/index.tsx
  src/components/common/WMConfirmationDialog/index.tsx
  src/components/common/dialogs/index.ts
  src/hooks/index.ts
  src/hooks/useEventListener.ts
  src/hooks/useRedirectToMain.ts
  src/providers/CourseEditorContext/utils.ts
  src/styles/variables.scss
  src/walkme/consts.ts
  src/walkme/screens/build.ts
Labels: code review

#153 Disable system menu in editor screen
  src/components/Layout/HeaderToolbar/SystemMenu.tsx
  src/components/Screen/CourseEditorScreen/index.tsx
Labels: code review

#154 Support non system users
  package.json
  src/components/Layout/HeaderToolbar/SystemMenu.tsx
  src/components/Screen/CoursesScreen/index.tsx
  src/hooks/useRedirectToMain.ts
  src/providers/AppContext/app-context.interface.ts
  src/providers/AppContext/utils.ts
Labels: code review

#162 Feedback fixes
  src/components/Layout/HeaderToolbar/utils.ts
  src/components/Screen/CourseEditorScreen/CourseItemDetails/index.tsx
  src/components/Screen/CourseEditorScreen/QuizHeader/index.tsx
  src/components/Screen/CourseEditorScreen/QuizSettingsForm/index.tsx
  src/components/Screen/CoursesScreen/index.tsx
Labels: code review

#160 Date range update
  src/components/Screen/CourseScreen/ExportCourseButton.tsx
  src/components/Screen/CourseScreen/index.tsx
  src/components/Screen/CoursesScreen/DeleteCoursesButton.tsx
  src/components/Screen/CoursesScreen/ExportCoursesButton.tsx
  src/components/Screen/CoursesScreen/ProductionStatusActions.tsx
  src/components/Screen/CoursesScreen/index.tsx
  src/components/Screen/UsersScreen/LoadMoreWrapper.tsx
  src/components/Screen/UsersScreen/index.tsx
  src/providers/AppContext/actions.ts
  src/providers/AppContext/app-context.interface.ts
  src/providers/AppContext/reducer.ts
  src/providers/CourseContext/actions.ts
  src/providers/CourseContext/course-context.interface.ts
  src/providers/CourseContext/reducer.ts
  src/providers/CoursesContext/actions.ts
  src/providers/CoursesContext/courses-context.interface.ts
  src/providers/CoursesContext/reducer.ts
  src/providers/UsersContext/actions.ts
  src/providers/UsersContext/reducer.ts
  src/providers/UsersContext/users-context.interface.ts
Labels: code review

#159 Link to support
  src/components/Layout/HeaderToolbar/index.tsx
  src/components/Screen/UsersScreen/LoadMoreWrapper.tsx
  src/providers/UsersContext/utils.ts
Labels: code review

#170 Add tooltip for segments cell
  src/components/Screen/CoursesScreen/style.module.scss
  src/components/Screen/CoursesScreen/tableData.tsx
  src/components/common/tableCells/LinkCell.tsx
  src/components/common/tableCells/TextArrayCell.tsx
Labels: code review

#156 Confirm course name with "enter" click
  package-lock.json
  src/components/common/EditableTitle/index.tsx
Labels: code review

#186 Quiz is enable implementation
  package-lock.json
  package.json
  src/components/Screen/CourseEditorScreen/ActionMenu.tsx
  src/components/Screen/CourseEditorScreen/CourseOutlineTab.tsx
  src/components/Screen/CourseEditorScreen/CourseSettingsTab/index.tsx
  src/components/Screen/CourseEditorScreen/QuizHeader/index.tsx
  src/components/Screen/CourseEditorScreen/QuizSettingsForm/index.tsx
  src/components/common/WMDropdown/style.module.scss
  src/components/common/buttons/AddButton/index.tsx
Labels: code review

#191 Adding percentage sign next to drop-off cell's value
  src/components/Screen/CourseScreen/tableData.tsx
Labels: code review

#194 QuizEditForm - changed prop onChange to onBlur
  src/components/Screen/CourseEditorScreen/QuizEditForm/QuestionScreenForm.tsx
  src/components/Screen/CourseEditorScreen/QuizEditForm/QuizScreenForm.tsx
Labels: code review

#193 Users table sorting
  src/components/Screen/UsersScreen/LoadMoreWrapper.tsx
  src/components/Screen/UsersScreen/ShownUsersIndicator.tsx
  src/components/Screen/UsersScreen/index.tsx
  src/components/Screen/UsersScreen/style.module.scss
  src/components/Screen/UsersScreen/tableData.tsx
  src/components/Screen/UsersScreen/utils.ts
  src/providers/UsersContext/actions.ts
  src/providers/UsersContext/index.tsx
  src/providers/UsersContext/reducer.ts
  src/providers/UsersContext/users-context.interface.ts
  src/providers/UsersContext/utils.ts
Labels: code review

#200 Styles changes
  src/components/Screen/CourseEditorScreen/QuizSettingsForm/index.tsx
  src/components/Screen/CourseScreen/CourseScreenHeader.tsx
  src/components/Screen/CourseScreen/style.module.scss
  src/components/Screen/CoursesScreen/index.tsx
  src/components/Screen/UsersScreen/index.tsx
  src/components/common/ScreenHeader/index.tsx
  src/components/common/ScreenHeader/style.module.scss
  src/components/common/WMTable/index.tsx
  src/components/common/WMTable/style.module.scss
  src/components/common/filters/TimeFilter/style.module.scss
  src/images/icons/sidebar-courses.svg
Labels: code review

#205 Segments tooltip
  src/components/Layout/Sidebar/style.module.scss
  src/components/Screen/CourseScreen/CourseScreenHeader.tsx
  src/components/Screen/CourseScreen/style.module.scss
  src/components/Screen/CoursesScreen/style.module.scss
  src/components/Screen/CoursesScreen/tableData.tsx
  src/components/common/ScreenHeader/style.module.scss
  src/components/common/WMPopover/style.module.scss
  src/components/common/WMTable/style.module.scss
  src/styles/index.scss
Labels: code review

#207 Users table filtering
  src/components/Screen/CourseEditorScreen/CourseSettingsTab/index.tsx
  src/components/Screen/UsersScreen/FiltersToolbar/index.tsx
  src/components/Screen/UsersScreen/FiltersToolbar/style.module.scss
  src/components/Screen/UsersScreen/LoadMoreWrapper.tsx
  src/components/Screen/UsersScreen/index.tsx
  src/components/Screen/UsersScreen/utils.ts
  src/components/common/WMSelect/index.tsx
  src/components/common/WMTable/style.module.scss
  src/providers/UsersContext/utils.ts
Labels: code review

#213 Drop off column alert icon
  package.json
  src/components/Screen/CourseScreen/CourseOutlineTable.tsx
  src/components/Screen/CourseScreen/CourseTabs.tsx
  src/components/Screen/CourseScreen/courseScreen.interface.ts
  src/components/Screen/CourseScreen/index.tsx
  src/components/Screen/CourseScreen/style.module.scss
  src/components/Screen/CourseScreen/tableData.tsx
  src/providers/CourseContext/course-context.interface.ts
  src/providers/CourseContext/reducer.ts
  src/providers/CourseContext/utils.ts
Labels: code review

#211 Limit course build width
  src/components/Screen/CourseEditorScreen/index.tsx
  src/components/Screen/CourseEditorScreen/style.module.scss
Labels: code review

#214 version 0.17.0
  package.json
  src/components/Screen/CourseEditorScreen/CourseSettingsTab/index.tsx
  src/components/Screen/CourseEditorScreen/index.tsx
  src/components/Screen/CourseEditorScreen/style.module.scss
  src/components/Screen/CourseScreen/CourseOutlineTable.tsx
  src/components/Screen/CourseScreen/CourseTabs.tsx
  src/components/Screen/CourseScreen/courseScreen.interface.ts
  src/components/Screen/CourseScreen/index.tsx
  src/components/Screen/CourseScreen/style.module.scss
  src/components/Screen/CourseScreen/tableData.tsx
  src/components/Screen/CoursesScreen/ActionsCell.tsx
  src/components/Screen/CoursesScreen/index.tsx
  src/components/Screen/CoursesScreen/style.module.scss
  src/components/Screen/CoursesScreen/tableData.tsx
  src/components/Screen/ErrorScreen/index.tsx
  src/components/Screen/UsersScreen/FiltersToolbar/index.tsx
  src/components/Screen/UsersScreen/FiltersToolbar/style.module.scss
  src/components/Screen/UsersScreen/LoadMoreWrapper.tsx
  src/components/Screen/UsersScreen/index.tsx
  src/components/Screen/UsersScreen/utils.ts
  src/components/common/Icon/icon.interface.ts
  src/components/common/Icon/iconsSVG.tsx
  src/components/common/WMSelect/index.tsx
  src/components/common/WMTable/style.module.scss
  src/images/icons/delete-small.svg
  src/images/icons/pencil-small.svg
  src/providers/CourseContext/course-context.interface.ts
  src/providers/CourseContext/reducer.ts
  src/providers/CourseContext/utils.ts
  src/providers/UsersContext/utils.ts
Labels: code review

#215 Fixing search input font-size
  src/components/common/dialogs/ImpersonateDialog/style.module.scss
Labels: code review

#216 Fixing analytics components data - treat zeros as valid data
  src/components/common/AnalyticsCharts/CourseTimeCompletionChart/index.tsx
  src/components/common/AnalyticsCharts/QuizCompletionRateChart/index.tsx
  src/components/common/AnalyticsCharts/QuizScoreChart/index.tsx
  src/components/common/AnalyticsCharts/analytics.interface.ts
  src/components/common/AnalyticsCharts/index.tsx
  src/components/common/charts/PieBarChart/index.tsx
  src/components/common/charts/PieBarSummary/index.tsx
  src/utils/index.ts
Labels: code review

#217 Users table updates
  src/components/Screen/UsersScreen/FiltersToolbar/index.tsx
  src/components/Screen/UsersScreen/FiltersToolbar/style.module.scss
  src/components/Screen/UsersScreen/index.tsx
  src/components/Screen/UsersScreen/style.module.scss
  src/components/Screen/UsersScreen/tableData.tsx
  src/styles/variables.scss
Labels: code review

#225 Adding user.editorAccountName to impersonate message
  src/components/Layout/HeaderToolbar/index.tsx
Labels: code review

#226 Changed the color of the WalkMe deployable icons
  src/components/Screen/CourseScreen/style.module.scss
  src/components/Screen/CourseScreen/tableData.tsx
Labels: code review

#227 Add `ScrollToTop` component
  src/components/Layout/index.tsx
  src/components/Screen/CourseScreen/index.tsx
  src/components/Screen/CourseScreen/style.module.scss
  src/components/common/ScrollToTop/index.tsx
  src/components/common/ScrollToTop/style.module.scss
Labels: code review

#228 Quiz data percentages
  package-lock.json
  package.json
  src/components/Layout/Sidebar/style.module.scss
  src/components/Screen/CourseScreen/CourseQuizEmptyState.tsx
  src/components/Screen/CourseScreen/CourseQuizTabCharts/index.tsx
  src/components/Screen/CourseScreen/CourseQuizTabCharts/style.module.scss
  src/components/Screen/CourseScreen/CourseTabs.tsx
  src/components/Screen/CourseScreen/style.module.scss
  src/components/common/AnalyticsCharts/QuizCompletionRateChart/index.tsx
  src/components/common/AnalyticsCharts/QuizScoreChart/index.tsx
  src/components/common/AnalyticsCharts/QuizScoreChart/style.module.scss
  src/components/common/AnalyticsCharts/style.module.scss
  src/components/common/CourseQuizTabCharts/index.tsx
  src/components/common/Icon/icon.interface.ts
  src/components/common/Icon/iconsSVG.tsx
  src/components/common/WMDialog/style.module.scss
  src/components/common/charts/WMHorizontalBarChart/index.tsx
  src/components/common/charts/WMHorizontalBarChart/style.module.scss
  src/images/icons/quiz-outline-empty.svg
  src/images/icons/quiz-tab.svg
  src/images/icons/quiz.svg
  src/images/icons/v-circle.svg
  src/styles/mixins.scss
  src/styles/variables.scss
Labels: code review

#235 Allow text selection
  src/styles/index.scss
Labels: code review

#237 Screen header content alignment fix
  src/components/Screen/CourseScreen/index.tsx
  src/components/Screen/CourseScreen/style.module.scss
Labels: bug, code review

#234 Unfocus add question button after click
  src/components/Screen/CourseEditorScreen/QuizHeader/index.tsx
  src/components/common/buttons/AddButton/index.tsx
Labels: bug, code review

#231 Error screen message
  src/App.tsx
  src/components/Screen/ErrorScreen/index.tsx
Labels: code review

#236 Course editor item settings description
  package.json
  src/components/Screen/CourseEditorScreen/CourseItemDetails/index.tsx
  src/components/Screen/Playground/components/CourseItemDetailsPanel.tsx
  src/components/common/WMRadio/WMVerticalRadioGroup.tsx
  src/components/common/WMRadio/interface.ts
  src/components/common/WMRadio/style.module.scss
Labels: code review

#238 Fixing v icon position in WMHorizontalBarChart
  src/components/common/charts/WMHorizontalBarChart/index.tsx
  src/components/common/charts/WMHorizontalBarChart/style.module.scss
Labels: code review

#239 Impersonate boomerang issue
  src/components/Layout/HeaderToolbar/index.tsx
  src/components/common/dialogs/ImpersonateDialog/style.module.scss
Labels: bug, code review

#240 Users table - quiz_result treat zeros as valid data
  src/components/Screen/UsersScreen/tableData.tsx
  src/components/common/tableCells/tableCells.interface.ts
Labels: bug, code review

#241 version 0.19.0
  package.json
  src/App.tsx
  src/components/Layout/HeaderToolbar/index.tsx
  src/components/Screen/CourseEditorScreen/CourseItemDetails/index.tsx
  src/components/Screen/CourseEditorScreen/QuizHeader/index.tsx
  src/components/Screen/CourseScreen/index.tsx
  src/components/Screen/CourseScreen/style.module.scss
  src/components/Screen/ErrorScreen/index.tsx
  src/components/Screen/Playground/components/CourseItemDetailsPanel.tsx
  src/components/Screen/UsersScreen/tableData.tsx
  src/components/common/WMRadio/WMVerticalRadioGroup.tsx
  src/components/common/WMRadio/interface.ts
  src/components/common/WMRadio/style.module.scss
  src/components/common/buttons/AddButton/index.tsx
  src/components/common/charts/WMHorizontalBarChart/index.tsx
  src/components/common/charts/WMHorizontalBarChart/style.module.scss
  src/components/common/dialogs/ImpersonateDialog/style.module.scss
  src/components/common/tableCells/tableCells.interface.ts
  src/constants/mocks/course-screen.ts
  src/constants/mocks/courseCompletionChartMock.ts
  src/constants/mocks/courseCompletionRateChartMock.ts
  src/constants/mocks/courseOutlineMock.tsx
  src/constants/mocks/courseSummaryChartMock.ts
  src/constants/mocks/courses-screen.ts
  src/constants/mocks/quizBarChart-mock.tsx
  src/constants/mocks/tableMockCoursesData.tsx
  src/constants/mocks/tableMockUsersData.tsx
  src/constants/mocks/users-mock.ts
  src/constants/routes.ts
  src/styles/index.scss
Labels: code review

#254 Update wm-message styles
  src/images/icons/check.svg
  src/styles/variables.scss
  src/utils/wmMessage/index.tsx
  src/utils/wmMessage/style.module.scss
Labels: bug, code review

#255 Quiz-score chart treat zero as valid score
  src/components/common/AnalyticsCharts/QuizScoreChart/index.tsx
  src/utils/index.ts
Labels: code review

#256 Quiz form fixes
  src/components/Screen/CourseEditorScreen/QuizEditForm/QuestionScreenForm.tsx
  src/components/Screen/CourseEditorScreen/QuizEditForm/QuizScreenForm.tsx
  src/components/Screen/CourseEditorScreen/QuizEditForm/index.tsx
Labels: bug, code review

#258 version 0.20.0
  package-lock.json
  package.json
  src/components/Layout/HeaderToolbar/SystemMenu.tsx
  src/components/Layout/HeaderToolbar/UserMenu.tsx
  src/components/Screen/CourseEditorScreen/CourseOutline.tsx
  src/components/Screen/CourseEditorScreen/CourseOutlineDetailsPanel.tsx
  src/components/Screen/CourseEditorScreen/CourseOutlineDetailsPanel/style.module.scss
  src/components/Screen/CourseEditorScreen/CourseOutlineQuiz/style.module.scss
  src/components/Screen/CourseEditorScreen/QuizEditForm/QuestionScreenForm.tsx
  src/components/Screen/CourseEditorScreen/QuizEditForm/QuizScreenForm.tsx
  src/components/Screen/CourseEditorScreen/QuizEditForm/index.tsx
  src/components/Screen/CourseEditorScreen/index.tsx
  src/components/Screen/CourseEditorScreen/style.module.scss
  src/components/Screen/UsersScreen/FiltersToolbar/index.tsx
  src/components/Screen/UsersScreen/FiltersToolbar/style.module.scss
  src/components/Screen/style.module.scss
  src/components/common/AnalyticsCharts/QuizScoreChart/index.tsx
  src/components/common/DetailsPanel/index.tsx
  src/components/common/DetailsPanel/style.module.scss
  src/components/common/dialogs/ImpersonateDialog/index.tsx
  src/components/common/tableCells/StatusDotCell.tsx
  src/hooks/useRedirectToMain.ts
  src/images/icons/check.svg
  src/providers/AppContext/actions.ts
  src/providers/AppContext/app-context.interface.ts
  src/providers/AppContext/reducer.ts
  src/providers/AppContext/utils.ts
  src/providers/CourseContext/utils.ts
  src/providers/CourseEditorContext/utils.ts
  src/providers/UsersContext/index.tsx
  src/providers/UsersContext/utils.ts
  src/styles/variables.scss
  src/utils/app-utils.ts
  src/utils/date.ts
  src/utils/index.ts
  src/utils/wmMessage/index.tsx
  src/utils/wmMessage/style.module.scss
  src/walkme/analytics/endpoint/index.ts
  src/walkme/index.ts
  src/walkme/models/users/list.ts
  src/walkme/screens/users.ts
  src/walkme/utils.ts
Labels: code review

#261 Round quiz answers percentage
  src/components/Screen/CourseScreen/CourseQuizTabCharts/index.tsx
  src/components/common/charts/WMHorizontalBarChart/index.tsx
Labels: bug, code review

#260 Fix wrong `%` placement in courses table column
  src/components/Screen/CoursesScreen/tableData.tsx
Labels: bug

#263 Fake checkbox cell
  package-lock.json
  package.json
  src/components/Screen/CoursesScreen/index.tsx
  src/components/Screen/CoursesScreen/style.module.scss
  src/components/Screen/CoursesScreen/tableData.tsx
  src/components/common/AnalyticsCharts/CourseSummaryChart/index.tsx
  src/components/common/AnalyticsCharts/CourseTimeCompletionChart/index.tsx
  src/components/common/AnalyticsCharts/QuizCompletionRateChart/index.tsx
  src/components/common/AnalyticsCharts/QuizScoreChart/index.tsx
  src/components/common/ScreenHeader/index.tsx
  src/components/common/WMTable/index.tsx
  src/components/common/WMTextarea/index.tsx
  src/components/common/tableCells/tableCells.interface.ts
  src/providers/CoursesContext/courses-context.interface.ts
  src/providers/CoursesContext/reducer.ts
Labels: code review

#259 Quiz charts state
  src/components/Layout/HeaderToolbar/EnvironmentMenu.tsx
  src/components/Layout/HeaderToolbar/SystemMenu.tsx
  src/components/Screen/CourseEditorScreen/QuizSettingsForm/index.tsx
  src/components/common/AnalyticsCharts/CourseTimeCompletionChart/index.tsx
  src/components/common/AnalyticsCharts/QuizCompletionRateChart/index.tsx
  src/components/common/AnalyticsCharts/QuizScoreChart/index.tsx
  src/components/common/AnalyticsCharts/utils.ts
  src/components/common/charts/PieBarChart/index.tsx
  src/walkme/data/overview/single.ts
  src/walkme/models/course/panels.ts
Labels: code review

#262 Update users-table columns-width so their titles would fit
  src/components/Screen/UsersScreen/style.module.scss
  src/components/common/tableCells/NumberCell.tsx
  src/components/common/tableCells/StatusDotCell.tsx
  src/components/common/tableCells/style.module.scss
Labels: bug, code review

#246 Add new resource
  src/components/Screen/CourseEditorScreen/ActionMenu.tsx
  src/components/Screen/CourseEditorScreen/CourseOutlineDetailsPanel.tsx
  src/components/Screen/CourseEditorScreen/CourseOutlineList/index.tsx
  src/components/Screen/CourseEditorScreen/CourseOutlineListEmptyState.tsx
  src/components/Screen/CourseEditorScreen/CourseOutlineQuiz/index.tsx
  src/components/Screen/CourseEditorScreen/CourseOutlineQuiz/style.module.scss
  src/components/Screen/CourseEditorScreen/CourseOutlineTab.tsx
  src/components/Screen/CourseEditorScreen/NewResourcePanel/NewResourceBaseForm.tsx
  src/components/Screen/CourseEditorScreen/NewResourcePanel/NewVideoForm.tsx
  src/components/Screen/CourseEditorScreen/NewResourcePanel/index.tsx
  src/components/Screen/CourseEditorScreen/NewResourcePanel/interface.ts
  src/components/Screen/CourseEditorScreen/NewResourcePanel/style.module.scss
  src/components/Screen/CourseEditorScreen/NewResourcePanel/utils.ts
  src/components/Screen/CourseEditorScreen/QuizEditForm/Answers.tsx
  src/components/Screen/CourseEditorScreen/QuizEditForm/QuestionScreenForm.tsx
  src/components/Screen/CourseEditorScreen/QuizEditForm/QuizScreenForm.tsx
  src/components/Screen/CourseEditorScreen/QuizEditForm/utils.ts
  src/components/Screen/CourseEditorScreen/QuizHeader/index.tsx
  src/components/Screen/CourseEditorScreen/QuizSettingsForm/index.tsx
  src/components/Screen/CourseEditorScreen/ResourcesList.tsx
  src/components/Screen/CourseEditorScreen/ResourcesListEmptyState.tsx
  src/components/Screen/CourseEditorScreen/index.tsx
  src/components/Screen/CourseEditorScreen/style.module.scss
  src/components/Screen/Playground/components/CourseItemDetailsPanel.tsx
  src/components/Screen/Playground/components/playground.module.scss
  src/components/Screen/Playground/index.tsx
  src/components/Screen/Playground/style.module.scss
  src/components/common/DetailsPanel/style.module.scss
  src/components/common/WMCollapse/style.module.scss
  src/components/common/WMRadio/WMVerticalRadioGroup.tsx
  src/components/common/buttons/AddButton/index.tsx
  src/components/common/buttons/AddButton/style.module.scss
  src/components/common/dialogs/PublishToEnvironmentDialog/index.tsx
  src/images/icons/lesson-small.svg
  src/images/icons/lesson.svg
  src/images/icons/quiz-settings.svg
  src/interfaces/index.ts
  src/providers/CourseEditorContext/course-editor-context.interface.ts
  src/styles/variables.scss
  src/utils/form.ts
  src/utils/index.ts
  src/utils/wmMessage/style.module.scss
Labels: code review
